Add the ability to customize curl options.
ttalle/dehydrated-vault-hook pull request #2
Opened 2020-03-23 21:09 UTC by ahpnils

Customizing curl options without editing the
script can be useful in some cases, depending on
the used vault setup. The new option set allows
a variety of setup, like redirects and
self-signed certificates, and we can remove the
silent option for debug purposes.

2020-04-02 11:51 UTC, ahpnils commented
Is there anything I should add, remove or fix ?

2020-09-28 20:37 UTC, ttalle requested changes

2020-09-28 20:37 UTC, ttalle commented on vault.example.inc
> +CURL_OPTS=(--silent --insecure --location)
Hey Nils, thank you for your contribution! Adding separate Curl options is a good idea, but adding --insecure as default in the example config seems like a bad precedent. Could you change that?

2020-09-28 20:40 UTC, ttalle commented
> Is there anything I should add, remove or fix ?

Hey Nils, I'm not much of a Github user so I submitted a change request but apparently it was stuck in _Pending_ state for six months (and obviously not visible for anyone else).

I've posted the change request. I think the default should be secure so if you can remove the --insecure from the default options I'm happy to merge this pull-request.

2020-09-29 12:38 UTC, ahpnils commented on vault.example.inc
> +CURL_OPTS=(--silent --insecure --location)
Hello, sorry about the insecure option. My latest commit should fix this.

2020-09-30 08:51 UTC, ttalle commented on vault.example.inc
> +CURL_OPTS=(--silent --insecure --location)
Great, thanks!

2020-09-30 08:51 UTC, ttalle approved these changes

2020-09-30 08:52 UTC, merged